### PR TITLE
added merge sort in python

### PR DESCRIPTION
**Pull request by bhaveshlohana**

### CODE REVIEW

**Comment by OtacilioN** [comment]
Hey, do you use MacOsx? I think we are with a problem in the repository for MacOsx users, your pull request is changing more than the files that you changed.

**Comment by OtacilioN** [comment]
I will be closing your pull request by now, and I will try to fix this problem, fell free to reopen it later.

**Comment by bhaveshlohana** [comment]
@OtacilioN hello, I had the same problem when someone sent a PR. In the files changed section, you can delete the files that get changed. And accept the merge sort one. I can do it again, but DigitalOcean would consider this PR spam then(and it'll also reset the Hacktoberfest timer.)

**Comment by OtacilioN** [comment]
Hey @bhaveshlohana, can you open a new pull request by adding the algorithm by the GitHub interface? Than I can approve it

**Comment by bhaveshlohana** [comment]
Yeah sure!

**Comment by CaioCordeiro** [comment]
@bhaveshlohana I'll be reviewing this PR now, could you explain a little bit what are you adding and removing? 😄

**Comment by OtacilioN** [comment]
Closing due to inactivity, feel free to reopen.

**Pull request closed without merging**
