### PR TITLE
Added 3D Cube transformations program

### PR DESCRIPTION
**Pull request by Yash-Punia**
Added 3D transformations on Cube program

Language used - C++
Library used - glut (can be installed using freeglut on linux)

Type in 
g++ cubeTransformations.cpp -o transform -lGL -lGLU -lglut && ./transform
to run the program.

### CODE REVIEW

**Comment by CaioCordeiro** [comment]
What a great code :smile: !
Thank you for contributing! :rocket:
I would separate this PR into 2 PRs, one for the '3D Cube' and another to the 'isEven'

**Comment by Yash-Punia** [comment]
Thank you!!! 😇
Yeah its great that way if they are in a separate PR.

**Comment by CaioCordeiro** [comment]
Can you rebase your code instead of merging it? So it doesn’t create a merge commit.

**Comment by Yash-Punia** [comment]
I just updated my repo, can you check again if there are conflicts?

**Pull request merged**
