### PR TITLE
Climbing stairs

### PR DESCRIPTION
**Pull request by nilaylilawala**
Climbing Stairs is a very famous DP Problem. 

->You are climbing a staircase. It takes n steps to reach the top.
Each time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?

Example 1:

Input: n = 2
Output: 2
Explanation: There are two ways to climb to the top.
1. 1 step + 1 step
2. 2 steps

### CODE REVIEW

**Comment by arun-kushwaha04** [comment]
Hey @nilaylilawala thanks for contribution. I need you to do few changes on your side. Create A new directory for Dynamic Programming Problem (name the directory as Dynamic Programming) and move your file in that. This help other users to add funny algorithms related to DP.

**Comment by nilaylilawala** [comment]
I am creating a new branch add-dp-directory. Please review it and a request to consider it as a hacktoberfest-accepted.

**Comment by arun-kushwaha04** [comment]
You got me wrong I mean currently the files are in `Climbing Stairs/climbing_stairs.cpp` move this a new directory dynamic programming so the file will be in `Dynamic Programming/Climbing Stairs/climbing_stairs.cpp`

**Comment by nilaylilawala** [comment]
Oh my bad. I will do it.

**Pull request closed without merging**
