### PR TITLE
Added balanced Parenthesis in python

### PR DESCRIPTION
**Pull request by Geeky-star**

### CODE REVIEW

**Comment by CaioCordeiro** [comment]
What a great code :smile: !
Just a little tip, its good to always put a description on your PRs to make more understandable.
Thank you for contributing! :rocket:

**Comment by Geeky-star** [comment]
> What a great code 😄 !
> Just a little tip, its good to always put a description on your PRs to make more understandable.
> Thank you for contributing! 🚀

Does that look like newbie code?

**Comment by CaioCordeiro** [comment]
> > What a great code smile !
> > Just a little tip, its good to always put a description on your PRs to make more understandable.
> > Thank you for contributing! rocket
> 
> Does that look like newbie code?

Not at all! Your code is clean, very organized and respects the OOP rules!

**Comment by Geeky-star** [comment]
> > > What a great code smile !
> > > Just a little tip, its good to always put a description on your PRs to make more understandable.
> > > Thank you for contributing! rocket
> > 
> > 
> > Does that look like newbie code?
> 
> Not at all! Your code is clean, very organized and respects the OOP rules! Congrats! 😄

Thankyou, happy to hear that😄

**Pull request merged**
