### PR TITLE
New Algorithm

### PR DESCRIPTION
**Pull request by Seggys116**

### CODE REVIEW

**Comment by internall** [comment]
You should add more comments.

**Comment by Seggys116** [comment]
> You should add more comments.

Sure. Will make changes soon

**Comment by Seggys116** [comment]
Done :)

**Comment by internall** [comment]
@OtacilioN

**Review by internall — APPROVED** [review]

**Comment by CaioCordeiro** [comment]
What a great code 😄 !
Just a little tip, it's good to always put a description on your PRs to make it more understandable.
Thank you for contributing! 🚀
Can you rename your commits to reflect what algorithm you are adding?

**Comment by OtacilioN** [comment]
Closing due to inactivity, feel free to reopen.

**Pull request closed without merging**
