### PR TITLE
Create EnglishAuction.sol

### PR DESCRIPTION
**Pull request by adielliot37**

### CODE REVIEW

**Comment by arun-kushwaha04** [comment]
@adielliot37 thanks for contributing.
Can you provide a brief description of the contract.

**Comment by adielliot37** [comment]
> @adielliot37 thanks for contributing. Can you provide a brief description of the contract.

uction
Seller of NFT deploys this contract.
Auction lasts for 7 days.
Participants can bid by depositing ETH greater than the current highest bidder.
All bidders can withdraw their bid if it is not the current highest bid.
After the auction
Highest bidder becomes the new owner of NFT.
The seller receives the highest bid of ETH.

**Comment by arun-kushwaha04** [comment]
Hey @adielliot37, can move `EnglishAuction.sol` to a new directory may be to `Solidity Contract/EnglishAuction.sol`. This will help other user to add new contracts.

**Comment by adielliot37** [comment]
ya that will be great

**Comment by OtacilioN** [comment]
Closing due to inactivity, feel free to reopen.

**Pull request closed without merging**
