### PR TITLE
Added Tree sorting

### PR DESCRIPTION
**Pull request by CodeXstalker**
@ReciHub I added sorting using BST.

### CODE REVIEW

**Comment by CodeXstalker** [comment]
@ReciHub please have look and consider to be merged

**Comment by SaiSudhaV** [comment]
Thank you for your contributions! Please check the comments and make necessary changes!

**Review by SaiSudhaV — CHANGES_REQUESTED** [review]

**Review by CodeXstalker — COMMENTED** [review]
@ReciHub It doesn't need to be necessary.
It would work fine.

**Review by SaiSudhaV — APPROVED** [review]

**Comment by SaiSudhaV** [comment]
Thank you for your contribution @CodeXstalker

**Pull request merged**
