### PR TITLE
Ellipse Drawing Algo in python

### PR DESCRIPTION
**Pull request by Vivekumar01**
Ellipse Drawing Algorithm in python using OpenGL.

### CODE REVIEW

**Comment by SaiSudhaV** [comment]
Hello @Vivekumar01 

Thank you for contributing. Can you please upload the screenshot of the output?

**Comment by Vivekumar01** [comment]
Should I make a different folder for the outputs and then put the outcomes in that? Or can I share over here?

**Comment by Vivekumar01** [comment]
Sir, I have put two outputs, please check the PR again.

**Comment by SaiSudhaV** [comment]
Great! good work Keep on contributing. Thank you

**Review by SaiSudhaV — APPROVED** [review]

**Pull request merged**
