### PR TITLE
added iseven.cpp

### PR DESCRIPTION
**Pull request by Lakshita2002**

### CODE REVIEW

**Comment by internall** [comment]
I'm not sure about the significance of this code.

**Comment by Lakshita2002** [comment]
@internall There is a folder "Is Even" which contains code to determine if the no. is even or not. Since it did not have any c++ code, I thought of adding it in.

**Comment by CaioCordeiro** [comment]
What a great code :smile: !
Just a little tip, its good to always put a description on your PRs to make more understandable.
Thank you for contributing! :rocket:

**Comment by Lakshita2002** [comment]
@CaioCordeiro I am so sorry for the trouble caused. I'll keep that in mind when making PRs in the future. Thank you for pointing it out :100: 
Happy Learning :tada:

**Comment by CaioCordeiro** [comment]
> @CaioCordeiro I am so sorry for the trouble caused. I'll keep that in mind when making PRs in the future. Thank you for pointing it out 100
> Happy Learning tada

No trouble caused at all, hahahahaha! 
Happy Learning :smile:

**Pull request merged**
