### PR TITLE
Banker's algo in Python along with its readme file of Bankers algorithm

### PR DESCRIPTION
**Pull request by Rac-Ro007**
Added python implementation of Banker's algorithm.
Readme becomes important for viewers to know what the algo is made for, added a readme file for banker's algo

### CODE REVIEW

**Comment by GrayFlash** [comment]
I went through your work and it seems valid to me. Although I will suggest you to write modular code if possible, since the repository is beginner-friendly I find it good to go.

**Comment by Rac-Ro007** [comment]
Sure, I will do it right away

**Comment by Rac-Ro007** [comment]
@GrayFlash , Do check the updated code. Thanks in advance, ( Grateful if u can attach hacktoberfest-accepted label to pr )

**Comment by GrayFlash** [comment]
Looks Good to go, Nicely Done. @Rac-Ro007 for now I can just acknowledge your PR cause I am not a Maintainer. @OtacilioN please merge this PR looks valid to me.

**Comment by SaiSudhaV** [comment]
@Rac-Ro007 I have gone through the code and it was good. I would like to suggest you to use list comprehension if possible so that it will make your code even more efficient.

**Comment by CaioCordeiro** [comment]
What a great code :smile: !
Thank you for contributing! :rocket:

**Pull request merged**
